// <auto-generated />
using System;
using IDelivery.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IDelivery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IDelivery.Domain.Tenants.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", "public");
                });

            modelBuilder.Entity("IDelivery.Domain.Tenants.Entities.Tenant", b =>
                {
                    b.OwnsOne("IDelivery.Domain.Tenants.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_number");

                            b1.Property<string>("Reference")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_reference");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants", "public");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("IDelivery.Domain.Common.ValueObjects.ZipCode", "ZipCode", b2 =>
                                {
                                    b2.Property<Guid>("AddressTenantId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("DigitsOnly")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("address_zip_code_digits");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(9)
                                        .HasColumnType("character varying(9)")
                                        .HasColumnName("address_zip_code");

                                    b2.HasKey("AddressTenantId");

                                    b2.ToTable("tenants", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressTenantId");
                                });

                            b1.Navigation("ZipCode")
                                .IsRequired();
                        });

                    b.OwnsOne("IDelivery.Domain.Tenants.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("_contactInfoExists")
                                .HasColumnType("boolean")
                                .HasColumnName("contact_info_exists");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants", "public");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("IDelivery.Domain.Common.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoTenantId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("contact_email");

                                    b2.HasKey("ContactInfoTenantId");

                                    b2.ToTable("tenants", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoTenantId");
                                });

                            b1.OwnsOne("IDelivery.Domain.Common.ValueObjects.PhoneNumber", "Phone", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoTenantId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("contact_phone");

                                    b2.HasKey("ContactInfoTenantId");

                                    b2.ToTable("tenants", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoTenantId");
                                });

                            b1.OwnsOne("IDelivery.Domain.Common.ValueObjects.PhoneNumber", "WhatsApp", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoTenantId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("contact_whatsapp");

                                    b2.HasKey("ContactInfoTenantId");

                                    b2.ToTable("tenants", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoTenantId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("Phone")
                                .IsRequired();

                            b1.Navigation("WhatsApp");
                        });

                    b.Navigation("Address");

                    b.Navigation("ContactInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
